// data/data.json is generated by the pipeline and gitignored.
// TypeScript accepts the import via this declaration; the cast in data.ts
// enforces the actual type (Athlete[]).
declare module "*.json" {
  const value: unknown;
  export default value;
}
