name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: biomejs/setup-biome@v2
        with:
          version: "2.4.4"
      - name: Run Biome
        run: biome ci .

  typecheck:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: CI
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: CI
        run: npm ci

      - name: Test
        run: npm run test:run
